### ISSUE TITLE
Images uploaded even if the prepare script errors out

### ISSUE THREAD

**Issue by imrehg** [balena-os/balena-yocto-scripts#128]
Even if this line throws an error:

https://github.com/balena-os/balena-yocto-scripts/blob/84c60eba818d4276d449692a3084f2c20e0eaae8/automation/jenkins_build.sh#L340

the script doesn't bail, as it's in a subshell.

**Comment by floion** [comment]
https://github.com/balena-os/balena-yocto-scripts/pull/133
@imrehg feel free to close this is satisfied
