### ISSUE TITLE
Question: What all those artifacts created by jenkins_build.sh?

### ISSUE THREAD

**Issue by siredmar** [balena-os/balena-yocto-scripts#140]
Hi,
i have a question regarding the jenkins_build.sh 
I successfully build an image and now have some artifacts lying around i don't know what to do with.
The artifacts generated by the scripts are:
```
./VERSION_HOSTOS
./VERSION
./kernel_source.tar.gz
./device-type.json
./image/balena.img.zip
./resin-image-raspberrypi3.manifest
./kernel_modules_headers.tar.gz

```

Now, i have no idea what do to with the following:
```
./VERSION_HOSTOS
./VERSION
./resin-image.docker
./device-type.json
```

Can anyone explain what's the purpose of those files in the context of building balenaOs?

**Comment by agherzan** [comment]
- ./VERSION_HOSTOS - used by balenacloud to indentfy the OS version of a deploy
- ./VERSION - used by balenacloud to indentfy the supevisor version in the OS version (above) of a deploy
- ./resin-image.docker - This the docker image export of the root filesystem of that specific release (we also push this to dockerhub resin/resinos or resin/resinos-staging)
- ./device-type.json - This is a device type description file which is used by balnenacloud
