### ISSUE TITLE
Should also upload the device logo.svg along with the rest of the deployed files

### ISSUE THREAD

**Issue by thgreasi** [balena-os/balena-yocto-scripts#142]
> we should update the [image deployment scripts](https://github.com/balena-os/balena-yocto-scripts) to also upload the device type's svg logo in the image release folder on S3. Initially we will include the logo under each release, so that we will need a minimal change to the current deployment process.
  Eg: https://resin-production-img-cloudformation.s3.amazonaws.com/images/am571x-evm/2.0.0-beta12.rev1/logo.svg

HQ: https://github.com/balena-io/balena/issues/1818

**Comment by floion** [comment]
Fixed by https://github.com/balena-os/balena-yocto-scripts/pull/145
