### ISSUE TITLE
Barys needs a clean build option

### ISSUE THREAD

**Issue by Langhalsdino** [balena-os/balena-yocto-scripts#165]
During the development of a new yocto build image, it is somentimes usefull to perform a clean build and ignore cached changes. Therefore I recommend to integrate the `--clean-build` flag similar to bitbake flags. 

Reference:
`-c clean`
`-c cleanall`
[Mega manual](https://www.yoctoproject.org/docs/2.2/mega-manual/mega-manual.html#ref-tasks-cleanall)

**Comment by Langhalsdino** [comment]
Just figured out that a ` -r|--remove-build` exists. It does a clean build right?

**Comment by floion** [comment]
Hi @Langhalsdino sorry for the late reply. Indeed, that option which you mentioned above does what you need.
