### ISSUE TITLE
barys: The development-image flag is broken by "update development image variables"

### ISSUE THREAD

**Issue by NGenetzky** [balena-os/balena-yocto-scripts#251]
## Summary

The `--development-image` flag has no effect because it is modifying a variable that does not exist in the TEMPLATECONF.

## Description

The `--development-image` flag should modify the `DEVELOPMENT_IMAGE` variable in `local.conf` but instead is attempting to modify `OS_DEVELOPMENT`.

- [balena-intel - meta-balena-genericx86 - local.conf.sample](https://github.com/balena-os/balena-intel/blob/ac3e7b8d53ec32c6c32471bc981de58ae2437acd/layers/meta-balena-genericx86/conf/samples/local.conf.sample#L16)

## Steps to reproduce 

This has been reproduced on the following commit, but is present in other versions.

- branch: master
- repo: [balena-intel](https://github.com/balena-os/balena-intel)
- commit bad651bb75b6e5c1c81254411ce16985ee75c79b
- tag: v2.83.18+rev4

```bash
YOCTO_DOWNLOADS="/mnt/downloads"
YOCTO_STATE_CACHE="/mnt/sstate-cache"

./balena-yocto-scripts/build/barys \
    -m 'genericx86-64-ext' \
    -k --rm-work --build-history --development-image \
    --shared-downloads "${YOCTO_DOWNLOADS}" \
    --shared-sstate "${YOCTO_STATE_CACHE}"
```

## Caused by

- #239 
- author: @markcorbinuk

```diff
tree 6767149740e887d4a759bcb7bf065f6771b4c9b5
parent b25459ffc7f5c8c22a6d5d7c3afd66d9dc691801
author Mark Corbin <mark@balena.io> Tue Oct 19 10:40:53 2021 +0000
committer Mark Corbin <mark@balena.io> Tue Oct 19 10:40:53 2021 +0000

barys: update development image variables

Update the DEVELOPMENT_IMAGE references to use OS_DEVELOPMENT
following the changes to the handling of OS variants.

Change-type: patch
Changelog-entry: barys: update development image variables
Signed-off-by: Mark Corbin mark@balena.io
diff --git a/build/barys b/build/barys
index 2ffaee1..8ed2bac 100755
--- a/build/barys
+++ b/build/barys
@@ -444,9 +444,9 @@ $SCRIPTPATH/generate-conf-notes.sh $SCRIPTPATH/../../layers/${BALENA_MACHINE_LAY
 export TEMPLATECONF=${SCRIPTPATH}/../../layers/${BALENA_MACHINE_LAYER}/conf/samples
 source ${SCRIPTPATH}/../../layers/poky/oe-init-build-env ${SCRIPTPATH}/../../${BUILD_DIR}
 if [ "x$DEVELOPMENT_IMAGE" == "xyes" ]; then
-    sed -i "s/.*DEVELOPMENT_IMAGE =.*/DEVELOPMENT_IMAGE = \"1\"/g" conf/local.conf
+    sed -i "s/.*OS_DEVELOPMENT =.*/OS_DEVELOPMENT = \"1\"/g" conf/local.conf
 else
-    sed -i "s/.*DEVELOPMENT_IMAGE =.*/DEVELOPMENT_IMAGE = \"0\"/g" conf/local.conf
+    sed -i "s/.*OS_DEVELOPMENT =.*/OS_DEVELOPMENT = \"0\"/g" conf/local.conf
     # Always activate resinhup bundles in production builds
     sed -i "s/.*RESINHUP ?=.*/RESINHUP ?= \"yes\"/g" conf/local.conf
 fi
```

**Comment by alexgg** [comment]
@NGenetzky device repositories will catch up with this change and replace `DEVELOPMENT_IMAGE` with `OS_DEVELOPMENT` as done for example in https://github.com/balena-os/balena-intel/commit/44be8f6ffeac510ee27455a5774bc4c984b5c3bb.

It's an old issue so you probably won't know what device type this issue referred to, so I am closing it for now but please re-open it with the extra details if it still needs addressing.

Also, we are usually much more responsive if you reach us through the forums (https://forums.balena.io) as we can then ask questions and gather extra details.
