### ISSUE TITLE
Yocto Dunfell supports new BitBake Syntax since August 2021

### ISSUE THREAD

**Issue by kmeinhar** [balena-os/balena-yocto-scripts#256]
BitBake in release Dunfell supports the new `:` syntax from version 1.46. See:
https://github.com/OSSystems/meta-browser/issues/543#issuecomment-912605725

I don't know the implications of adding that to `NEW_SYNTAX_RELEASES=("honister" "kirkstone")` in `build/barys`.
Since there are now Dunfell releases with and without `:` syntax it could cause issues downstream. I still think it might be worth investigating.

**Comment by alexgg** [comment]
This is now resolved - we perform a syntax conversion for device types that are on releases older than Honister.
